name: MCAdministration
version: 1.2.1
main: me.zee.mcadministration.MCAdministration
author: Zee
depend: [Vault]

commands:
  kick:
    description: Kicks a player with a given reason
  slay:
    description: Slays a player with a given reason
    aliases: [kill]
  sethealth:
    description: Sets a player's health to a value with a given reason
    aliases: [sethp]
  warn:
    description: Warns a player with a given reason
  mute:
    description: Mutes a player with a given reason
  unmute:
    description: Unmutes a player
  ban:
    description: Bans a player with a given reason
  tempban:
    description: Temporarily bans a player with a given reason
  unban:
    description: Unbans a player
  announce:
    description: Announces a message to the server
    aliases: [ann, broadcast]
  invsee:
    description: View a player's inventory with a given reason
  viewban:
    description: View a specific ban
  register:
    description: Register an account with the server
  setrank:
    description: Set the new rank of a given user
  changepassword:
    description: Change the password for a player's server account
    aliases: [changepass, changepw]
  stats:
    description: View the info saved about a registered player
